### ISSUE TITLE
New Repo Transfer

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/GlowstonePlusPlusOldFork#4]
@jlirochon You may now proceed transfering the new repo. ;)

**Comment by jlirochon** [comment]
The patched version is not working as is. I think it's a cache problem with CircleCI. Anyway, I will reimport the old one as a branch, so the commit hash still works.

I'm doing this right now !

**Comment by jlirochon** [comment]
Ok 7b4fb9f2b608e7a79b527c7d0cc53aa62da07821 is still valid on the new repo. I can't transfer it to **DragonetMC** because GitHubs keeps saying I'm not an admin of it. I transfered it to you @DefinitlyEvil

**Comment by jlirochon** [comment]
Please add me as a contributor when done, I have still work in progress on this

**Comment by DefinitlyEvil** [comment]
I will add you to the owner now. ;)

**Comment by DefinitlyEvil** [comment]
Since you have lot of expirence on programming.

**Comment by jlirochon** [comment]
thank you ;)

**Comment by DefinitlyEvil** [comment]
Also becuz I don't have much time doing this project recently, so you can be the vice-head-developer. lol

**Comment by RandomAltThingy** [comment]
Just make a branch for the old one....duh

**Comment by RandomAltThingy** [comment]
Make me owner too I'm still in developers

**Comment by jlirochon** [comment]
@RandomAltThingy the old repository was not recognized as a fork by GitHub, see the title, it does not mention "forked from GlowstonePlusPlus/GlowstonePlusPlus", that's why we created this one.
